# Generated by Django 5.1.6 on 2025-02-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecart', '0002_remove_ecart_user_remove_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
